//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace FindExpert.UI.Infrastructure.Resources.Localization {


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Errors_ru {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("FindExpert.UI.Infrastructure.Resources.Localization.Errors.ru", typeof(Errors_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Срок действия кода подтверждения истёк.
        /// </summary>
        public static string CONFIRM_EMAIL_CONFIRMATION_CODE_EXPIRED {
            get {
                return ResourceManager.GetString("CONFIRM_EMAIL_CONFIRMATION_CODE_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутренняя ошибка сервера при подтверждении email.
        /// </summary>
        public static string CONFIRM_EMAIL_EMAIL_CONFIRMATION_FAILED {
            get {
                return ResourceManager.GetString("CONFIRM_EMAIL_EMAIL_CONFIRMATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указан неверный код подтверждения.
        /// </summary>
        public static string CONFIRM_EMAIL_INVALID_CODE {
            get {
                return ResourceManager.GetString("CONFIRM_EMAIL_INVALID_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email данного пользователя уже подтверждён.
        /// </summary>
        public static string CONFIRM_EMAIL_USER_EMAIL_ALREADY_CONFIRMED {
            get {
                return ResourceManager.GetString("CONFIRM_EMAIL_USER_EMAIL_ALREADY_CONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с указанным email не найден.
        /// </summary>
        public static string CONFIRM_EMAIL_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("CONFIRM_EMAIL_USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email не подтверждён. Пожалуйста, проверьте вашу почту.
        /// </summary>
        public static string LOGIN_EMAIL_NOT_CONFIRMED {
            get {
                return ResourceManager.GetString("LOGIN_EMAIL_NOT_CONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден или неверный пароль.
        /// </summary>
        public static string LOGIN_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOGIN_USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недействительный refresh token: истёк или имеет неверный формат.
        /// </summary>
        public static string LOGOUT_REFRESH_TOKEN_INVALID {
            get {
                return ResourceManager.GetString("LOGOUT_REFRESH_TOKEN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сессия с указанным refresh token не найдена.
        /// </summary>
        public static string LOGOUT_SESSION_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOGOUT_SESSION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недействительный refresh token: истек или имеет неверный формат.
        /// </summary>
        public static string REFRESH_INVALID_REFRESH_TOKEN {
            get {
                return ResourceManager.GetString("REFRESH_INVALID_REFRESH_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активная сессия с указанным refresh token не найдена.
        /// </summary>
        public static string REFRESH_SESSION_NOT_FOUND {
            get {
                return ResourceManager.GetString("REFRESH_SESSION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указанный email уже зарегистрирован.
        /// </summary>
        public static string REGISTER_EMAIL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("REGISTER_EMAIL_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email уже зарегистрирован, но не подтверждён.
        /// </summary>
        public static string REGISTER_EMAIL_REGISTERED_NOT_CONFIRMED {
            get {
                return ResourceManager.GetString("REGISTER_EMAIL_REGISTERED_NOT_CONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при повторной отправке кода подтверждения.
        /// </summary>
        public static string RESEND_CONFIRMATION_CODE_FAILED {
            get {
                return ResourceManager.GetString("RESEND_CONFIRMATION_CODE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указанный email уже подтверждён.
        /// </summary>
        public static string RESEND_CONFIRMATION_CODE_USER_EMAIL_ALREADY_CONFIRMED {
            get {
                return ResourceManager.GetString("RESEND_CONFIRMATION_CODE_USER_EMAIL_ALREADY_CONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с указанным email не найден.
        /// </summary>
        public static string RESEND_CONFIRMATION_CODE_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("RESEND_CONFIRMATION_CODE_USER_NOT_FOUND", resourceCulture);
            }
        }
    }
}
